# -*- coding: utf-8 -*-
"""Amazon ML Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyZk5whzOGNB5Asw-mpM7aWkyWqhNVoN

Baseline Price Prediction Notebook (script-style)
Generates test_out.csv for the Smart Product Pricing Challenge.

Cells are separated by "# %%" markers so you can run this as a script or convert to a notebook.
Dependencies:
  pip install pandas scikit-learn lightgbm numpy scipy joblib tqdm
Optional (for image features): pip install torch torchvision timm pillow

Usage:
  - Place this file at the repo root alongside the `dataset/` folder.
  - Run: python baseline_price_prediction_notebook.py

Outputs:
  - test_out.csv
  - artifacts/: saved vectorizers, SVDs, scaler, trained models (joblib / lightgbm)
"""

# %%
# Imports and basic utilities
import os
import re
import gc
import json
from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
import lightgbm as lgb
import joblib
import warnings
warnings.filterwarnings('ignore')

ARTIFACT_DIR = Path('artifacts')
ARTIFACT_DIR.mkdir(exist_ok=True)

# SMAPE metric
def smape(y_true, y_pred):
    y_true = np.asarray(y_true, dtype=float)
    y_pred = np.asarray(y_pred, dtype=float)
    denom = (np.abs(y_true) + np.abs(y_pred)) / 2.0
    # avoid division by zero
    mask = denom == 0
    denom[mask] = 1.0
    return np.mean(np.abs(y_pred - y_true) / denom) * 100.0

# %%
# IPQ extraction heuristic
def extract_ipq(text):
    if pd.isna(text) or len(str(text).strip()) == 0:
        return 1
    text = str(text)
    patterns = [
        r'(\d+)\s*[-]?\s*pack',
        r'pack\s*of\s*(\d+)',
        r'(\d+)\s*ct\b',
        r'(\d+)\s*pcs?\b',
        r'quantity[:\s]+(\d+)',
        r'(\d+)\s*pieces?\b',
        r'(\d+)\s*x\s*\d+'
    ]
    for p in patterns:
        m = re.search(p, text, flags=re.I)
        if m:
            try:
                val = int(m.group(1))
                if 1 <= val <= 10000:
                    return val
            except:
                pass
    m = re.search(r'(\d+)', text)
    if m:
        v = int(m.group(1))
        if 1 <= v <= 10000:
            return v
    return 1

import pandas as pd

print("Loading data safely...")
train = pd.read_csv("/content/train.csv", engine="python", quoting=3, on_bad_lines="skip")
test = pd.read_csv("/content/test.csv", engine="python", quoting=3, on_bad_lines="skip")

print(f"train: {train.shape}, test: {test.shape}")

# %%
# Basic preprocessing and feature creation
for df in (train, test):
    df['catalog_content'] = df['catalog_content'].fillna('').astype(str)
    df['ipq'] = df['catalog_content'].apply(extract_ipq)
    df['len_chars'] = df['catalog_content'].str.len()
    df['len_words'] = df['catalog_content'].str.split().str.len().fillna(0)
    df['num_digits'] = df['catalog_content'].str.count(r'\d')
    df['num_caps'] = df['catalog_content'].str.count(r'[A-Z]')
    df['num_special'] = df['catalog_content'].str.count(r'[^0-9A-Za-z\s]')

# Target transform
train['price'] = pd.to_numeric(train['price'], errors='coerce').fillna(0)
train['price'] = train['price'].clip(lower=0)
train['log_price'] = np.log1p(train['price'])

# %%
# Text vectorizers - fit on combined text
print('Fitting TF-IDF vectorizers...')
all_text = pd.concat([train['catalog_content'], test['catalog_content']])
word_tfidf = TfidfVectorizer(max_features=50000, ngram_range=(1,2), analyzer='word', min_df=3)
char_tfidf = TfidfVectorizer(max_features=10000, ngram_range=(3,6), analyzer='char', min_df=5)

word_tfidf.fit(all_text)
char_tfidf.fit(all_text)

joblib.dump(word_tfidf, ARTIFACT_DIR / 'word_tfidf.joblib')
joblib.dump(char_tfidf, ARTIFACT_DIR / 'char_tfidf.joblib')

# %%
# Transform and reduce via SVD (memory-safe version)
from scipy.sparse import vstack

print("Transforming text and applying SVD (memory-safe)...")

# Stack sparse matrices vertically instead of converting to dense arrays
word_X_all = vstack([word_X, word_X_test])
char_X_all = vstack([char_X, char_X_test])

# Initialize SVD models
svd_words = TruncatedSVD(n_components=128, random_state=42)
svd_chars = TruncatedSVD(n_components=64, random_state=42)

# Fit on combined sparse data (train + test) to capture full variance
svd_words.fit(word_X_all)
svd_chars.fit(char_X_all)

# Transform the original train and test matrices
train_word_svd = svd_words.transform(word_X)
train_char_svd = svd_chars.transform(char_X)
test_word_svd = svd_words.transform(word_X_test)
test_char_svd = svd_chars.transform(char_X_test)

# Save models
joblib.dump(svd_words, ARTIFACT_DIR / "svd_words.joblib")
joblib.dump(svd_chars, ARTIFACT_DIR / "svd_chars.joblib")

print("SVD transformation complete.")
print(f"train_word_svd: {train_word_svd.shape}, train_char_svd: {train_char_svd.shape}")
print(f"test_word_svd:  {test_word_svd.shape},  test_char_svd:  {test_char_svd.shape}")

# %%
# Transform text data using fitted vectorizers
print("Transforming text data...")
word_X = word_tfidf.transform(train['catalog_content'])
word_X_test = word_tfidf.transform(test['catalog_content'])
char_X = char_tfidf.transform(train['catalog_content'])
char_X_test = char_tfidf.transform(test['catalog_content'])

print(f"word_X: {word_X.shape}, word_X_test: {word_X_test.shape}")
print(f"char_X: {char_X.shape}, char_X_test: {char_X_test.shape}")

# %%
# Assemble features
num_cols = ['ipq','len_chars','len_words','num_digits','num_caps','num_special']
X_num = train[num_cols].values
X_num_test = test[num_cols].values

X_train = np.hstack([X_num, train_word_svd, train_char_svd])
X_test = np.hstack([X_num_test, test_word_svd, test_char_svd])

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
joblib.dump(scaler, ARTIFACT_DIR / 'scaler.joblib')

y = train['log_price'].values

# %%
# CV training with LightGBM (compatible with new API)
import lightgbm as lgb
from sklearn.model_selection import StratifiedKFold
import numpy as np
import pandas as pd
import joblib, gc

print("Starting CV training...")

# stratify by price bins
bins = pd.qcut(y, q=10, duplicates="drop", labels=False)
kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

oof = np.zeros(len(train))
preds = np.zeros(len(test))
models = []

for fold, (tr_idx, val_idx) in enumerate(kf.split(X_train, bins)):
    print(f"\n=== Fold {fold+1} ===")
    X_tr, X_val = X_train[tr_idx], X_train[val_idx]
    y_tr, y_val = y[tr_idx], y[val_idx]

    train_data = lgb.Dataset(X_tr, label=y_tr)
    val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

    params = {
        "objective": "regression",
        "metric": "rmse",
        "learning_rate": 0.05,
        "num_leaves": 127,
        "min_data_in_leaf": 50,
        "feature_fraction": 0.8,
        "bagging_fraction": 0.8,
        "bagging_freq": 5,
        "seed": 42 + fold,
        "verbosity": -1,
    }

    # Use callbacks for logging and early stopping
    callbacks = [
        lgb.early_stopping(stopping_rounds=100),
        lgb.log_evaluation(period=200)
    ]

    model = lgb.train(
        params,
        train_data,
        valid_sets=[train_data, val_data],
        num_boost_round=5000,
        callbacks=callbacks
    )

    val_pred = model.predict(X_val, num_iteration=model.best_iteration)
    oof[val_idx] = val_pred
    preds += model.predict(X_test, num_iteration=model.best_iteration) / kf.n_splits
    models.append(model)

    # Save per-fold model
    model.save_model(str(ARTIFACT_DIR / f"lgb_fold{fold+1}.txt"))

    del train_data, val_data, X_tr, X_val, y_tr, y_val
    gc.collect()

joblib.dump(models, ARTIFACT_DIR / "lgb_models.joblib")
print("CV training complete.")

# %%
# Evaluate OOF using SMAPE on original price scale
oof_price = np.expm1(oof)
true_price = train['price'].values
print('OOF SMAPE (%):', smape(true_price, oof_price))

# %%
# Final predictions and save
test_pred_price = np.expm1(preds)
test_pred_price = np.clip(test_pred_price, 0.01, None)

out = pd.DataFrame({'sample_id': test['sample_id'], 'price': test_pred_price})
out.to_csv('test_out.csv', index=False)
print('Saved test_out.csv')

# Save a small json summary
summary = {
    'oof_smape_percent': float(smape(true_price, oof_price)),
    'num_train': int(len(train)),
    'num_test': int(len(test))
}
with open(ARTIFACT_DIR / 'summary.json', 'w') as f:
    json.dump(summary, f, indent=2)

print('Done. Artifacts in', ARTIFACT_DIR)

# %%
# Optional: helper function to extract image embeddings (requires torch & timm)
# Uncomment and run if you installed torch, timm and want to generate image features.
"""
# %%
import torch
from PIL import Image
import timm
from torchvision import transforms

def extract_image_embeddings(image_paths, model_name='resnet50', batch_size=64, device='cuda'):
    model = timm.create_model(model_name, pretrained=True)
    model.reset_classifier(0)
    model.eval()
    model.to(device)
    preprocess = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    embeddings = []
    with torch.no_grad():
        for i in range(0, len(image_paths), batch_size):
            batch_paths = image_paths[i:i+batch_size]
            imgs = []
            for p in batch_paths:
                try:
                    img = Image.open(p).convert('RGB')
                    imgs.append(preprocess(img))
                except Exception as e:
                    imgs.append(torch.zeros(3,224,224))
            imgs = torch.stack(imgs).to(device)
            emb = model(imgs)
            embeddings.append(emb.cpu().numpy())
    return np.vstack(embeddings)

# Example usage:
# image_files = list(Path('images').glob('*.jpg'))
# emb = extract_image_embeddings([str(p) for p in image_files])
# np.save('artifacts/image_embeddings.npy', emb)
"""